name: Manually publish to a registry

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry name'
        required: true
        type: choice
        options:
          - npmjs

jobs:
  npm-publish:
    if:  ${{ inputs.registry == 'npmjs' }}
    permissions:
      id-token: write
    uses: ./.github/workflows/npm-publish.yml
